import { NextResponse } from 'next/server';

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const prompt = body.prompt;

    if (!prompt) {
      return NextResponse.json(
        { success: false, error: 'Prompt is required' },
        { status: 400 }
      );
    }

    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      return NextResponse.json(
        { success: false, error: 'GEMINI_API_KEY is not configured' },
        { status: 500 }
      );
    }

    const apiUrl = 'https://generativelanguage.googleapis.com/v1beta/models/imagen-3.0-generate-002:predict?key=' + apiKey;

    const response = await fetch(apiUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        instances: [
          {
            prompt: prompt,
          },
        ],
        parameters: {
          sampleCount: 1,
          aspectRatio: '1:1',
          outputOptions: {
            mimeType: 'image/jpeg',
          },
        },
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error('Gemini API Error:', errorText);
      return NextResponse.json(
        { success: false, error: 'Gemini API error: ' + response.status },
        { status: response.status }
      );
    }

    const data = await response.json();

    if (!data.predictions || data.predictions.length === 0) {
      return NextResponse.json(
        { success: false, error: 'No image generated by Gemini' },
        { status: 500 }
      );
    }

    const base64Image = data.predictions[0].bytesBase64Encoded;
    const mimeType = data.predictions[0].mimeType || 'image/jpeg';
    const resultBase64 = 'data:' + mimeType + ';base64,' + base64Image;

    return NextResponse.json({
      success: true,
      result_base64: resultBase64,
    });
  } catch (error: any) {
    console.error('Generate Image Route Error:', error);
    return NextResponse.json(
      { success: false, error: error.message || 'Failed to generate image' },
      { status: 500 }
    );
  }
}
